#!/bin/bash
KNIFESUCCESS=1
REGION=`curl http://169.254.169.254/latest/dynamic/instance-identity/document 2>/dev/null|grep region|awk -F\" '{print $4}'`
sudo curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 1.3.43
chef gem install knife-ec2
if [ ! -f .chef/knife.rb ] || [ ! -f .chef/*.pem ]; then
  echo "You have not put your chef pem file and knife.rb file in place.  Exiting."
  exit 1
fi
while [ $KNIFESUCCESS -ne 0 ]; do
  echo "Please provide the security group ID (i.e. sg-7cd06507)"
  read SG
  echo "Please provide your AWS Access Key ID:"
  read AWSKEYID
  echo "Please provide your AWS Secret Access Key:"
  read -s AWSKEY
  cp .chef/knife.rb .chef/knife.rb.orig
  cat >> .chef/knife.rb << EOF 
knife[:aws_access_key_id] = "$AWSKEYID"
knife[:aws_secret_access_key] = "$AWSKEY"
EOF
  knife ec2 server list --region $REGION >/dev/null 2>&1
  KNIFESUCCESS=$?
  if [ $KNIFESUCCESS -ne 0 ]; then
    cp .chef/knife.rb.orig .chef/knife.rb
    clear
    echo "I was unable to authenticate with that info.  Please try again."
  fi
done

knife ssl check
RETURN=$?
if [ $RETURN -ne 0 ]; then
  echo "Something is wrong with your ssl config.  You probably loaded the wrong key into .chef.  Try again."
  exit 1
fi
knife cookbook upload dexcom_chef_httpd
berks install
berks upload
knife role from file roles/web.json

cat > new_EC2_webserver << EOF 
#!/bin/bash
knife ec2 server create -r "role[web]" -I  ami-d2c924b2 -f t2.micro -S dexcom -i ~/.ssh/dexcom.pem --ssh-user centos --region $REGION -g $SG
EOF
chmod +x new_EC2_webserver

echo "You should now be be able to run new_EC2_webserver to automatically launch an EC2 instance and configure it to complete the challenge."
